-- Gitee 上公开的 Java 项目清单，给页面上的仓库下拉框当数据源。
-- 数据来自 Gitee 的 /orgs/{org}/repos 与 /users/{user}/repos（按 star 降序取前 200）。
-- 之所以要落库：仓库搜索接口 /search/repositories 现在对任何请求都只返回 total_count 0，
-- 页面上那个「搜项目」的下拉框没有数据源了。想加项目直接往这张表里 insert 即可。
-- 现在这张表是**兜底**：正常路径是实时拉令牌能访问的仓库（GiteeClient#listMyRepos，
-- 也就是你自己账号下的那些）。只有令牌没配/失效/网络不通时才会退回这份清单。
-- 用 INSERT IGNORE：schema/data 每次启动都会重跑，靠 full_name 的唯一键保证幂等。

INSERT IGNORE INTO review_repo_catalog (full_name, name, description, stars, created_at) VALUES
('zhijiantianya/ruoyi-vue-pro', 'ruoyi-vue-pro', '🔥 官方推荐  🔥 RuoYi-Vue 全新 Pro 版本，优化重构所有功能。基于 Spring Boot + MyBatis Plus + Vue & Element 实现的后台管理系统 + 微信小程序，支持 RBAC动态权限、数据权', 111645, NOW()),
('zhijiantianya/yudao-cloud', 'yudao-cloud', 'ruoyi-vue-pro 全新 Cloud 版本，优化重构所有功能。基于 Spring Cloud Alibaba + Gateway+Nacos+RocketMQ + Vue&Element 实现的后台管理系统 + 用户小程序，支持RB', 73701, NOW()),
('dromara/sa-token', 'Sa-Token', '✨ 开源、免费、一站式 java 权限认证框架，让鉴权变得简单、优雅！—— 登录认证、权限认证、分布式 Session 会话、微服务网关鉴权、SSO 单点登录、OAuth2.0 统一认证、jwt 集成、API 参数签名、API Key 秘钥', 49404, NOW()),
('log4j/pig', 'pig', '基于Spring Boot 4.1、 Spring Cloud 2025 & Alibaba、 SAS OAuth2 的微服务RBAC 权限管理系统。 🔝 🔝   记得上边点个star 关注更新。 微服务交流群见底部二维码。', 45789, NOW()),
('macrozheng/mall', 'mall', '🔥🔥🔥mall项目是一套基于 SpringBoot + Vue + uni-app 的电商系统，包括前台商城项目及后台管理系统，采用Docker容器化部署。前台商城系统包含首页门户、商品推荐、商品搜索、商品展示、购物车、订单流程、会员', 27260, NOW()),
('kekingcn/file-online-preview', 'kkFileView', '使用spring boot打造文件文档在线预览项目解决方案，支持doc、docx、ppt、pptx、wps、xls、xlsx、zip、rar、ofd、xmind、bpmn 、eml 、epub、3ds、dwg、psd 、mp4、mp3以及众', 24169, NOW()),
('dromara/RuoYi-Vue-Plus', 'RuoYi-Vue-Plus', '多租户后台管理系统 重写RuoYi-Vue所有功能 集成 Sa-Token、Mybatis-Plus、WarmFlow、SpringDoc、Hutool、OSS 定期同步', 16984, NOW()),
('stylefeng/guns', 'Guns', 'Guns v8.3.0发布，全新前后端分离版本。Guns是一个现代化的Java应用开发基础框架，基于主流技术Spring Boot3 + JDK17，配套代码生成平台，DevOps运维平台，CI/CD持续集成能力，在线API接口管理。', 16392, NOW()),
('dromara/MaxKey', 'MaxKey', 'Dromara MaxKey™🗝️单点登录认证系统是业界领先的IAM-IDaas身份管理和认证产品，遵循Apache-2.0开源免费，支持OAuth2.x、OpenID Connect、SAML2.0、CAS、JWT、SCIM等SSO标准', 14609, NOW()),
('xuxueli0323/xxl-job', 'xxl-job', '一个分布式任务调度平台，其核心设计目标是开发迅速、学习简单、轻量级、易扩展。现已开放源代码并接入多家公司线上产品线，开箱即用。', 14146, NOW()),
('dromara/Jpom', 'Jpom', 'dromara jpom-简而轻的低侵入式在线构建、自动部署、日常运维、项目运维监控软件', 12016, NOW()),
('baomidou/mybatis-plus', 'mybatis-plus', 'mybatis 增强工具包，简化 CRUD 操作。 文档 http://baomidou.com 低代码组件库 http://aizuda.com', 11654, NOW()),
('yadong.zhang/JustAuth', 'JustAuth', '小而全而美的第三方登录开源组件。目前已支持Github、Gitee、微博、钉钉、百度、Coding、腾讯云开发者平台、OSChina、支付宝、QQ、微信、淘宝、Google、Facebook、抖音、领英、小米、微软、今日头条、Teambit', 10533, NOW()),
('dromara/easyAi', 'EasyAi', '国内人气最高的Java人工智能算法框架(java版pytorch)。它可以Maven一键丝滑引入我们的Java项目，无需任何额外的环境配置与依赖，做到开箱即用。再者，它既有一些我们已经封装好的图像目标检测及人工智能客服的模块，也提供各种深度', 9298, NOW()),
('jfinal/jfinal', 'JFinal', 'JFinal 是基于 Java 语言的极速 WEB + ORM 框架，其核心设计目标是开发迅速、代码量少、学习简单、功能强大、轻量级、易扩展、Restful。在拥有Java语言所有优势的同时再拥有ruby、python、php等动态语言的开', 8937, NOW()),
('dromara/open-capacity-platform', 'open-capacity-platform', '简称ocp是基于Spring Cloud的企业级微服务框架(用户权限管理，配置中心管理，应用管理，....),其核心的设计目标是分离前后端，快速开发部署，学习简单，功能强大，提供快速接入核心接口能力，其目标是帮助企业搭建一套类似百度能力开放', 8877, NOW()),
('dromara/warm-flow', 'warm-flow', 'Dromara Warm-Flow，国产的工作流引擎，以其简洁轻量、五脏俱全、灵活扩展性强的特点，成为了众多开发者的首选。它不仅可以通过jar包快速集成设计器，同时原生支持经典和仿钉钉双模式', 8735, NOW()),
('dromara/liteFlow', 'liteFlow', '轻量、快速、稳定、可编排的组件式规则引擎，更能支持 AI Agent 像普通组件一样自由编排进业务流程。拥有独有设计的 DSL 规则表达式，支持组件复用、同步/异步与动态编排、超多语言脚本、复杂嵌套规则、热部署与平滑刷新——你会编排 Lit', 7569, NOW()),
('dromara/RuoYi-Cloud-Plus', 'RuoYi-Cloud-Plus', '微服务管理系统 重写RuoYi-Cloud所有功能 整合 SpringCloudAlibaba、Dubbo3.0、Sa-Token、Mybatis-Plus、MQ、WarmFlow、ES、Docker 全方位升级 定期同步', 7186, NOW()),
('Tencent/APIJSON', 'APIJSON', '🏆  实时 零代码、全功能、强安全 ORM 库 🚀 后端接口和文档零代码，前端(客户端) 定制返回 JSON 的数据和结构', 6660, NOW()),
('aizuda/flowlong', 'flowlong', '🔥🔥🔥飞龙工作流 FlowLong 🐉 真正的国产、无代码工作流引擎、低代码集成、支持AI智能体审批，功能比飞书钉钉审批流程更加强大🚩为中国特色审批匠心打造❗', 6356, NOW()),
('dromara/easy-es', 'easy-es', 'Elasticsearch 国内Top1 elasticsearch搜索引擎框架es ORM框架,索引全自动智能托管,如丝般顺滑,与Mybatis-plus一致的API,屏蔽语言差异,开发者只需要会MySQL语法即可完成对Es的相关操作,零', 5795, NOW()),
('dromara/lamp-cloud', 'lamp-cloud', 'lamp-cloud 基于jdk21、jdk17、jdk8 + SpringCloud + SpringBoot 开发的微服务中后台快速开发平台，专注于多租户(SaaS架构)、开放平台解决方案，亦可作为普通项目（非SaaS架构）的基础开发框', 5718, NOW()),
('dromara/northstar', 'northstar', '一站式平替TradingView、盘立方、文华量化的交易软件', 4428, NOW()),
('dromara/ujcms', 'ujcms', 'Java开源网站内容管理系统(java cms)。使用SpringBoot、MyBatis、Vue3、ElementPlus、Vite、TypeScript等技术开发。支持无头CMS，支持可视化、可查询自定义字段，支持信创。', 4420, NOW()),
('baomidou/dynamic-datasource-spring-boot-starter', 'dynamic-datasource', '基于 SpringBoot 多数据源 动态数据源 主从分离 快速启动器 支持分布式事务', 4394, NOW()),
('dromara/tianai-captcha', 'tianai-captcha', '可能是java界最好的开源行为验证码 captcha、captcha、captcha、captcha、tianai-captcha [滑块验证码、点选验证码、行为验证码、旋转验证码， 滑动验证码]', 4212, NOW()),
('dromara/forest', 'forest', '声明式与编程式双修的 HTTP 客户端框架，让 Java 再没有难以发送的 HTTP 请求', 3926, NOW()),
('aizuda/snail-job', 'snail-job', '🔥🔥🔥 灵活，可靠和快速的分布式任务重试和分布式任务调度平台', 3588, NOW()),
('seagull1985/LuckyFrameWeb', 'LuckyFrameWeb', 'LuckyFrame测试平台是一款免费开源的测试平台，最大的特点是全纬度覆盖了接口自动化、WEB UI自动化、APP自动化，并且支持分布式测试，测试关键字驱动也很大程度上解决了测试同学代码基础弱的问题。同时也集成了质量管理相关的一些功能，解', 3535, NOW()),
('dromara/skyeye', 'skyeye-oa', 'Skyeye云企业级AI+零代码，采用Springboot + UNI-APP + Ant Design Vue的框架的快速开发平台。包含CRM、PM、ERP、MES、ADM、OA、EHR、AI、项目、商城、财务、多班次考勤、薪资、招聘、云', 3515, NOW()),
('dromara/surpass', 'surpass', 'Dromara Surpass API权限开放平台，面向REST API资源无状态认证和调用，实现企业统一权限管理；零代码开发，SQL定义RESTful OpenAPI接口，支持JWT、RBAC资源权限管理，Swagger自动生成等，遵循A', 3480, NOW()),
('xuxueli0323/xxl-sso', 'xxl-sso', 'XXL-SSO 是一个 单点登录框架，只需要登录一次就可以访问所有相互信任的应用系统。具备 “轻量级、高扩展、渐进式” 的等特性，支持 “登录认证、权限认证、角色认证、分布式会话认证、单点登录、Web常规登录、前后端分离” 等多登录及认证类', 3477, NOW()),
('dromara/TLog', 'TLog', '一个轻量级的分布式日志标记追踪神器，10分钟即可接入，自动对日志打标签完成微服务的链路追踪', 3419, NOW()),
('fit2cloud-feizhiyun/DataEase', 'DataEase', '🔥 人人可用的开源 BI 工具，数据可视化神器。', 3332, NOW()),
('dromara/dante-cloud', 'dante-cloud', '🐉 Dante Cloud 是支持阻塞式与响应式服务并行的微服务云原生基座和面向AI Agent开发的智能基座，基于领域驱动模型（DDD）设计，以高质量代码与低安全漏洞为核心，高度模块化、组件化，覆盖IoT设备认证、国家等保三级、接口国密', 3301, NOW()),
('yudaocode/SpringBoot-Labs', 'SpringBoot-Labs', '一个涵盖六个专栏：Spring Boot 2.X、Spring Cloud、Spring Cloud Alibaba、Dubbo、分布式消息队列、分布式事务的仓库。希望胖友小手一抖，右上角来个 Star，感恩 1024', 3296, NOW()),
('dromara/zyplayer-doc', 'zyplayer-doc', 'zyplayer-doc是一款专注于个人与企业私有化部署使用的知识库、WIKI文档管理系统，丰富的功能可满足企业几乎所有的文档管理场景需求。', 3215, NOW()),
('stylefeng/roses', 'Roses', 'Roses基于Spring Boot 3 + JDK17，是开源项目Guns的核心支撑层。', 3113, NOW()),
('dromara/x-file-storage', 'x-file-storage', '一行代码将文件存储到 本地、FTP、SFTP、WebDAV、谷歌云、阿里云OSS、华为云OBS、七牛云Kodo、腾讯云COS、百度云 BOS、又拍云USS、MinIO、 AWS S3、FastDFS、 Azure Blob Storage、', 2997, NOW()),
('dromara/mendmix-cloud', 'mendmix-cloud', 'Mendmix-cloud定位是一站式云原生架构技术底座。Mendmix-cloud提供了数据库、缓存、消息中间件、分布式定时任务、安全框架、网关以及主流产商云服务快速集成能力。基于Mendmix-cloud可以不用关注技术细节快速搭建高并', 2732, NOW()),
('dromara/mica-mqtt', 'mica-mqtt', 'mqtt client 和 mqtt broker 基于 java aio 实现，开源、简单、易用、低延迟、高性能百万级 java mqtt client 组件和 java mqtt broker 服务。降低自研 iot 物联网平台难度。�', 2628, NOW()),
('aizuda/panshi', 'panshi', '🔥🔥🔥panshi 磐石，稳定可靠的 Web 开发框架。 出处：《荀子·劝学》“锲而不舍，金石可镂”', 2588, NOW()),
('dromara/dynamic-tp', 'dynamic-tp', '🔥🔥🔥轻量级动态线程池，内置监控告警功能，基于主流配置中心（已支持Nacos、Apollo、ZK，可通过SPI自定义实现）。Lightweight dynamic threadpool, with monitoring and ala', 2559, NOW()),
('WeBank/DataSphereStudio', 'DataSphereStudio', '将满足从数据交换、脱敏清洗、分析挖掘、质量检测、可视化展现、定时调度到数据输出等数据应用开发全流程场景需求。欢迎申请体验demo环境：https://sandbox.webank.com/wds/dss/#/register', 2452, NOW()),
('dromara/dbswitch', 'dbswitch', 'dbswitch是一款完全开源的异构数据库迁移同步(搬家)工具', 2383, NOW()),
('baomidou/kisso', 'kisso', 'java 基于 Cookie 的 SSO 中间件 kisso  低代码组件库 https://doc.aizuda.com/docs/sso.html', 2369, NOW()),
('lionsoul/jcseg', 'jcseg', 'Jcseg是基于mmseg算法的一个轻量级Java中文分词器，同时集成了关键字提取，关键短语提取，关键句子提取和文章自动摘要等功能，并且提供了一个基于Jetty的web服务器，方便各大语言直接http调用，同时提供了最新版本的lucene、', 2291, NOW()),
('dromara/J2EEFAST', 'J2eeFAST', 'J2eeFAST 是一个 Java EE 企业级快速开发平台，致力于打造中小企业最好用的开源免费的后台框架平台。 系统基于（Spring Boot、Spring MVC、Apache Shiro、MyBatis-Plus、Freemarke', 2237, NOW()),
('dromara/sms4j', 'SMS4J', '让简单的事情回归简单的本质。 SMS4J为短信聚合框架，帮您轻松集成多家短信服务，解决接入多个短信SDK的繁琐流程。 目前已接入数家常见的短信服务商，后续将会继续集成。后续的版本中我们还将推出更多的相关功能 你的 ⭐️ ⭐️⭐️Star⭐️', 2134, NOW()),
('dromara/neutrino-proxy', 'neutrino-proxy', 'NeutrinoProxy(中微子代理) 一款基于solon、netty的内网穿透神器！', 2133, NOW()),
('dromara/wgai', 'WGAI', '免费，本地化，开箱即用的WebAI离线训练识别平台：人脸识别&数字人 &OCR&语音识别平台不仅限于( 图片和各种视频流（rtsp、rtmp、flv）识别，可自主训练任意场景一键训练，融合了AI图像识别opencv、yolo3-26、ocr', 2123, NOW()),
('dromara/koalas-rpc', 'koalas-rpc', '小而美高可用可拓展的RPC框架。理论上并发数量接近服务器带宽，客户端采用thrift协议，服务端支持netty和thrift的TThreadedSelectorServer半同步半异步线程模型，支持动态扩容，服务上下线，权重动态，可用性配置', 2049, NOW()),
('dromara/x-easypdf', 'x-easypdf', 'pdf一站式解决方案', 2026, NOW()),
('baomidou/lock4j', 'lock4j', '基于Spring AOP 的声明式和编程式分布式锁，支持RedisTemplate、Redisson、Zookeeper', 1968, NOW()),
('dromara/image-combiner', 'image-combiner', 'ImageCombiner是一个专门用于Java服务端图片合成的工具，没有很复杂的功能，简单实用，从实际业务场景出发，提供简单的接口，几行代码即可实现图片拼合（当然用于合成水印也可以），素材上支持图片、文本、矩形三种，支持定位、缩放、旋转、', 1953, NOW()),
('dromara/hmily', 'hmily', '金融级分布式事务解决方案', 1944, NOW()),
('dromara/cubic', 'cubic', '一站式问题定位平台，还在为线上问题而烦恼吗？实时线程栈监控、线程池监控、动态arthas命令集、依赖分析等等等，助你快速定位问题', 1932, NOW()),
('dromara/dax-pay', 'dax-pay', '支持支付宝、微信、抖音、乐刷等通道，提供支付、退款、风控、分账等功能。通过HTTP方式进行调用，不与其他系统产生耦合关联，提供可视化界面进行管理。', 1921, NOW()),
('opengoofy/hippo4j', 'hippo4j', '🚀 异步线程池框架，支持线程池动态变更&监控&报警，无需修改代码轻松引入。', 1909, NOW()),
('macrozheng/mall-swarm', 'mall-swarm', 'mall-swarm是一套微服务商城系统，采用了 Spring Cloud Alibaba、Spring Boot 3.5、Sa-Token、MyBatis、Elasticsearch、Docker、Kubernetes等核心技术，同时提供', 1875, NOW()),
('seagull1985/LuckyFrameClient', 'LuckyFrame', 'LuckyFrame测试平台是一款免费开源的测试平台，最大的特点是全纬度覆盖了接口自动化、WEB UI自动化、APP自动化，并且支持分布式测试，测试关键字驱动也很大程度上解决了测试同学代码基础弱的问题。同时也集成了质量管理相关的一些功能，解', 1855, NOW()),
('sofastack/sofa-boot', 'sofa-boot', 'SOFABoot 是蚂蚁集团开源的基于 Spring Boot 的研发框架，它在 Spring Boot 的基础上，提供了诸如 Readiness Check，类隔离，日志空间隔离等等能力。', 1811, NOW()),
('dromara/easy_trans', 'easy_trans', '本公司提供数据中台(数据治理平台)源代码对外出售、包含元数据、数据源、数据治理、数据标准、数据标签、数据服务、数据质量、数据开发采集、数据资产、数据可视化等功能，基于kettle和flink，欢迎了解。easy-trans是一款数据翻译插件', 1775, NOW()),
('aizuda/rule-engine-open', 'rule-engine-open', '🔥🔥🔥📌 可视化规则引擎开源版 📌  RuleEngine  基于Web可视化配置，简单高效快捷。业务逻辑实现不再依赖于代码开发，可零代码实现复杂业务逻辑!', 1745, NOW()),
('dromara/omega-ai', 'Omega-AI', 'Omega-AI：基于java打造的深度学习框架，帮助你快速搭建神经网络，实现模型推理与训练，引擎支持自动求导，多GPU训练，GPU支持CUDA，CUDNN。', 1532, NOW()),
('dromara/free-fs', 'free-fs', '🔥Free-FS 开源文件管理系统：基于 Spring Boot 4.x的企业级网盘系统。支持分片上传、断点续传、秒传、文件分享、在线预览。集成阿里云OSS、七牛云Kodo、S3体系、本地存储等多种存储方式。提供文件管理、用户权限、存储配', 1493, NOW()),
('aizuda/data-platform-open', 'data-platform-open', '🔥🔥🔥可视化拖拽式大数据集成平台、大数据平台、大数据，包含数据流、数据源、数据对齐、查询模板、智能问数、AI集成、完善的监控等。像画流程图一样且无代码方式同步、清洗数据。', 1464, NOW()),
('dromara/orion-visor', 'orion-visor', '一款高颜值、现代化的自动化运维及轻量堡垒机，提供全面的服务器智能运维解决方案。支持资产管理分组、多协议访问(SSH、SFTP、RDP、VNC)、实时系统监控与智能告警、文件上传下载、在线编辑、命令批量执行、多主机文件分发和计划任务配置(通过', 1446, NOW()),
('aizuda/mongo-plus', 'MongoPlus', '🔥🔥🔥使用MyBatisPlus的方式，优雅的操作MongoDB', 1362, NOW()),
('fit2cloud-feizhiyun/MeterSphere', 'MeterSphere', 'MeterSphere 是新一代的开源持续测试工具，让软件测试工作更简单、更高效，不再成为持续交付的瓶颈。', 1244, NOW()),
('aizuda/lingclaw', 'lingclaw', '🔥🔥🔥 lingclaw 是一个大模型+小模型的AI中台，可以被多系统多平台接入，提供完备的AI能力。大模型+小模型可以弥补大模型垂直领域不足，如小模型人脸识别，识别成功结果告诉大模型，以便更好的交互效果', 1126, NOW()),
('dromara/dy-java', 'DyJava', 'DyJava 是一款功能强大的抖音 Java 开发工具包（SDK），支持抖音各个应用 OpenAPI 快速调用，包括但不限于移动/网站应用、抖音开放平台、抖店、TikTok 和抖音小程序等。DyJava 致力于简化开发流程，提高开发效率，让', 1098, NOW()),
('dromara/sureness', 'sureness', '面向REST API的高性能认证鉴权框架，致力于管理保护API安全', 974, NOW()),
('sofastack/sofa-bolt', 'sofa-bolt', 'SOFABolt 是蚂蚁集团开发的一套基于 Netty 实现的网络通信框架。', 973, NOW()),
('dromara/sayOrder', 'SayOrder', '该项目是基于easyAi引擎的JAVA高性能，低成本，轻量级智能客服。可与用户自动对话，自动捕捉订单信息，分辨用户需求，自动生成订单。也可自动回答用户疑问，提供处理需求的问答服务，是全网速度最快的java开源智能自主客服！', 958, NOW()),
('dromara/payment-spring-boot', 'payment-spring-boot', '微信支付V3支付，支持微信优惠券，代金券、商家券、公众号支付、微信小程序支付、分账、支付分、商家券、合单支付、先享卡、电商收付通等全部微信支付功能API，同时满足服务商、商户开发需求。一键集成，上手快，欢迎star。', 954, NOW()),
('dromara/gobrs-async', 'gobrs-async', '🚀🔥🚀 多线程并发编程框架。为企业高并发（电商）复杂场景提供快速解决方案。 可以完美应对多种多线程高并发场景。 如果苦恼于多线程开发，赶快体验下吧！', 939, NOW()),
('xuxueli0323/xxl-api', 'xxl-api', '一个强大易用的API管理平台，提供API的"管理"、"文档"、"Mock"和"测试"等功能。', 938, NOW()),
('kekingcn/spring-boot-klock-starter', 'spring-boot-klock-starter', '基于redis的分布式锁组件，简单方便快捷接入项目，使项目拥有分布式锁能力', 875, NOW()),
('aizuda/snail-ai', 'snail-ai', 'Snail AI 企业级 AI Agent 平台 - 让 AI 更智能，让开发更高效', 853, NOW()),
('macrozheng/mall-learning', 'mall-learning', 'mall学习教程，架构、业务、技术要点全方位解析。mall项目（60k+star）是一套电商系统，使用现阶段主流技术实现。涵盖了SpringBoot、MyBatis 、Elasticsearch、RabbitMQ、Redis、MongoDB', 850, NOW()),
('WeBank/wecube-platform', 'wecube-platform', 'WeCube是一套开源的，一站式IT架构管理和运维管理工具，主要用于简化分布式架构IT管理，并可以通过插件进行功能扩展。', 846, NOW()),
('dromara/sqlrest', 'sqlrest', 'SQLREST是一款完全开源的SQL转 RESTful API的SQL2API低代码工具', 815, NOW()),
('baomidou/MybatisX', 'MybatisX', 'MybatisX 快速开发插件，文档 https://baomidou.com/guides/mybatis-x/', 813, NOW()),
('kekingcn/kk-anti-reptile', 'kk-anti-reptile', '可快速接入的反爬虫、接口防盗刷spring boot stater组件', 810, NOW()),
('dromara/myth', 'myth', '采用消息队列解决分布式事务的开源框架, 基于java语言来开发（JDK1.8），支持dubbo，springcloud,motan等rpc框架进行分布式事务。', 792, NOW()),
('xuxueli0323/xxl-conf', 'xxl-conf', 'XXL-CONF 是一个分布式配置中心与注册中心，提供 动态配置管理、服务注册与发现 等核心能力；拥有 “轻量级、秒级实时推送、多环境、跨语言、跨机房、权限控制” 等特性。', 763, NOW()),
('sofastack/sofa-rpc', 'sofa-rpc', 'SOFARPC 是一个高可扩展性、高性能、生产级的 Java RPC 框架。在蚂蚁金服 SOFARPC 已经经历了十多年及五代版本的发展。', 750, NOW()),
('dromara/RedisFront', 'RedisFront', 'RedisFront 是一款基于 Java Swing 开发的跨平台 Redis 客户端工具，兼容多种主流操作系统 ( 包括 Windows, macOS 和 Linux ) , 通过可视化界面实现 Redis 数据管理与服务器状态监测，适', 727, NOW()),
('aizuda/zlm4j', 'zlm4j', '🔥🔥🔥基于ZLMediaKit C API封装， 几行代码搭建流媒体服务器', 693, NOW()),
('dromara/stream-query', 'stream-query', '允许完全摆脱Mapper的mybatis-plus体验！可以使用类似“工具类”这样的静态函数进行数据库操作', 634, NOW()),
('WeBank/Qualitis', 'Qualitis', 'Qualitis是一个支持多种异构数据源的质量校验、通知、管理服务的数据质量管理平台，用于解决业务系统运行、数据中心建设及数据治理过程中的各种数据质量问题。 Qualitis基于Spring Boot，依赖于Linkis进行数据计算，提供', 628, NOW()),
('dromara/mybatis-plus-ext', 'mybatis-plus-ext', 'mybatis-plus框架的拓展包，在框架原有基础上做了进一步的轻度封装，增强内容：免手写Mapper、多数据源自动建表、数据自动填充、自动关联查询、冗余数据自动更新、动态查询条件等。', 619, NOW()),
('baomidou/kaptcha-spring-boot-starter', 'kaptcha-spring-boot-starter', '基于 SpringBoot Google Kaptcha 验证码 快速启动器', 613, NOW()),
('Tencent/spring-cloud-tencent', 'spring-cloud-tencent', 'Spring Cloud Tencent 是腾讯提供的一套 Spring Cloud 解决方案，包含核心的服务注册发现、配置中心、限流、路由、熔断等常用的服务治理能力', 602, NOW()),
('xuxueli0323/xxl-mq', 'xxl-mq', '一款轻量级分布式消息队列，支持 "并发消息、串行消息、广播消息、延迟消息、事务消息、失败重试、超时控制" 等消息特性。现已开放源代码，开箱即用。', 572, NOW()),
('xuxueli0323/xxl-crawler', 'xxl-crawler', '一个分布式爬虫框架。一行代码开发一个分布式爬虫，拥有"多线程、异步、IP动态代理、分布式、JS渲染"等特性；', 568, NOW()),
('dromara/MilvusPlus', 'MilvusPlus', '🔥🔥🔥使用MyBatisPlus的方式，优雅的操作向量数据库 Milvus，同时支持spring和solon', 534, NOW()),
('dromara/easy-query', 'easy-query', 'java最强orm没有之一(支持kotlin)零sql纯面向对象关系', 511, NOW()),
('dromara/Raincat', 'Raincat', '2阶段提交分布式事务中间件（Implement by 2 pc）', 499, NOW()),
('WeBank/Exchangis', 'Exchangis', 'Exchangis是微众银行开源的轻量级数据交换平台，用于数据在不同存储介质中快速传递，并解决数据交换过程中面临的复杂性、兼容性等问题。设计上采取微服务架构形态，上下层服务松耦合，易于进行个性化的，高拓展性的迭代开发。', 485, NOW()),
('dromara/disjob', 'disjob', '一款分布式的任务调度与分布式计算框架', 463, NOW()),
('jfinal/enjoy', 'enjoy', 'Enjoy 是基于 Java 语言的极度轻量级模板引擎。仅 227 KB 并且不依赖任何第三方。极简设计仅 if、for、switch、set、define、include、render 七个核心指令，令学习成本低到极致。 Enjoy co', 453, NOW()),
('dromara/fast-request', 'fast-request', 'IntelliJ plugin Restful Fast Request，IDEA上类似postman的工具', 435, NOW()),
('xuxueli0323/xxl-rpc', 'xxl-rpc', '一个分布式服务框架，提供稳定高性能的RPC远程服务调用功能。拥有"高性能、分布式、注册中心、软负载、服务治理"等特性。现已开放源代码，开箱即用。', 421, NOW()),
('baomidou/jobs', 'jobs', 'jobs 分布式任务调度组件', 416, NOW()),
('sofastack/sofa-tracer', 'sofa-tracer', 'SOFATracer 是一个用于分布式系统调用跟踪的组件，通过统一的 traceId 将调用链路中的各种网络调用情况以日志的方式记录下来，以达到透视化网络调用的目的。这些日志可用于故障的快速发现，服务治理等。', 398, NOW()),
('dromara/TestHub', 'TestHub', 'TestHub是一个创新的开源自动化测试工具，它通过引入流程编排功能，采用结构化和模块化的方法，TestHub能够将测试用例表示为一系列可执行的流程，从而实现测试的自动化和标准化。彻底改变了测试过程的管理与执行方式。该工具以其插件式架构和直', 392, NOW()),
('dromara/WeMQ', 'WeMQ', 'WeMQ是一款面向物联网设备运营商的开源物联网设备调试系统，提供完整的物联网设备调试方案，集成设备管理、MQTT服务器管理、客户管理等功能，自研Nmqs通信层组件，实现了连接信息的加密，保证了数据的安全性。', 391, NOW()),
('stylefeng-Roses/roses-kernel', 'roses-kernel', 'roses-kernel 微服务框架的核心，利用spring boot自动配置，提供项目开发所需要的大部分配置，提供代码生成，jwt验证工具类，日志记录工具类，资源扫描，签名，参数校验等等！业务开发的利器！', 380, NOW()),
('xuxueli0323/xxl-tool', 'xxl-tool', 'XXL-TOOL 是一个Java工具类库，致力于让Java开发更高效。包含 “集合、字符串、缓存、IO、并发、Excel、Emoji、Response、Pipeline、Http、Json、JsonRpc、Encrypt、Auth……” 等', 378, NOW()),
('dromara/data-compare', 'dataCompare', '大数据比对和数据探测平台：低代码平台、数据对比和数据探测', 340, NOW()),
('WeBank/we-cmdb', 'we-cmdb', 'WeCMDB（Configuration Management Database 配置管理数据库），是源自微众银行运维管理实践的的一套配置管理数据库系统。', 333, NOW()),
('baomidou/mybatisplus-spring-mvc', 'mybatisplus-spring-mvc', 'Mybatis-Plus SpringMVC 演示 demo', 312, NOW()),
('baomidou/hibernate-plus', 'hibernate-plus', 'Hibernate 增强工具包 - 只做增强不做改变，更加精简持久层CRUD操作', 301, NOW()),
('aizuda/easy-manager-tool', 'easy-manager-tool', '🔥🔥🔥五星上将麦克阿瑟都觉得好用的一款对于软件从业者好用的管理工具，包括服务器管理，ssh，sftp，docker，监控，告警，脚本管理等，当个堡垒机也可以玩玩', 298, NOW()),
('xuxueli0323/xxl-cache', 'xxl-cache', 'XXL-CACHE 是一个 多级缓存框架，高效组合本地缓存和分布式缓存(Redis+Caffeine)，支持“多级缓存、一致性保障、TTL、Category隔离、防穿透”等能力；拥有“高性能、高扩展、灵活易用”等特性，提供高性能多级缓存解决', 294, NOW()),
('baomidou/mybatisplus-maven-plugin', 'mybatisplus-maven-plugin', 'Mybatis-Plus Maven 代码生成插件', 290, NOW()),
('baomidou/shaun', 'shaun', '基于 pac4j-jwt 的 WEB 安全组件', 289, NOW()),
('yudaocode/yudao-demo', 'yudao-demo', '芋道快速开发平台的 UI 静态项目，用于快速体验，无需前端 Node 等环境', 286, NOW()),
('kekingcn/kkbinlog', 'kkbinlog', '支持mysql、MongoDB数据变更订阅分发', 270, NOW()),
('baomidou/mybatisplus-boot-starter', 'mybatisplus-spring-boot-starter', 'mybatis-plus spring-boot 版本', 252, NOW()),
('javen205/jfinal_qyweixin', 'jfinal_qyweixin', 'jfinal_qyweixin是基于 jfinal-weixin二次开发而来，只需浏览 Demo 代码即可进行极速开发。同时支持微信企业号以及企业微信', 248, NOW()),
('WeBank/Visualis', 'Visualis', 'Visualis是一个基于宜信的开源项目Davinci开发的数据可视化BI工具。现已被集成到数据应用开发门户DataSphere Studio中。 Visualis支持拖拽式报表定义、图表联动、钻取、全局筛选、多维分析、实时查询等数据', 224, NOW()),
('xuxueli0323/xxl-boot', 'xxl-boot', 'A fast development platform.（XXL-BOOT 是一个快速开发平台，易学易用、简化开发、丰富扩展、开箱即用。整合前后端流行技术，致力为 中小企业、个人开发者 打造开箱即用的中后台解决方案）', 217, NOW()),
('WeBank/Schedulis', 'Schedulis', 'Schedulis 是微众银行基于 LinkedIn 的开源项目 Azkaban 开发的一款工作流任务调度系统，用于解决金融级场景下，大量批量作业任务的复杂依赖、灵活调度。', 215, NOW()),
('WeBank/DeFiBus', 'DeFiBus', 'DeFiBus=RPC+MQ，是基于开源消息中间件打造的安全可控的分布式金融级消息总线。DeFiBus不仅提供了RPC同步调用，还提供了MQ的异步事件通知、事件组播和广播等常用服务调用和消息模式，同时增加了应用多中心多活、服务就近、灰度发布', 211, NOW()),
('opengoofy/crane4j', 'crane4j', '一个简单易用的关联字段填充框架，通过简单的注解配置快速根据外键/编码值填充相关字段，支持字典，枚举，方法等多种数据源。', 206, NOW()),
('kekingcn/kkbida', 'kkbida', '解决异构系统间消息通知时保证消息必达', 197, NOW()),
('dromara/auto-table', 'AutoTable', 'Java最强数据库构建框架，超越JPA，根据 Java 实体，自动创建数据库、表、索引。', 188, NOW()),
('sofastack/sofa-ark', 'sofa-ark', 'SOFAArk 是一款基于 Java 实现的轻量级类隔离容器，主要提供类隔离和应用（模块）动态部署能力', 176, NOW()),
('sofastack/sofa-jraft', 'sofa-jraft', 'SOFAJRaft 是一个基于 RAFT 一致性算法的生产级高性能 Java 实现，支持 MULTI-RAFT-GROUP，适用于高负载低延迟的场景', 160, NOW()),
('WeBank/EventMesh', 'eventmesh', 'Event Mesh是一个动态的插件式云原生基础服务层，用于分离应用程序和中间件层。它提供了灵活，可靠和快速的事件分发，并且可以进行管理。 目前EventMesh已经进入Apache软件基金会孵化器，成为孵化项目。', 152, NOW()),
('dromara/mybatis-jpa-extra', 'mybatis-jpa-extra', '扩展MyBatis JPA支持，标准CRUD操作，高效SELECT分页查询，让MyBatis拥有JPA的优雅体验。Extended MyBatis JPA support , standard CRUD operations and eff', 148, NOW()),
('baomidou/kisso-spring-boot', 'kisso-spring-boot', 'kisso SpringBoot 演示 demo', 132, NOW()),
('stylefeng/guns-generator', 'guns-generator', 'guns代码生成器', 114, NOW()),
('WeBank/WeCross', 'WeCross', 'WeCross是由微众银行自主研发并完全开源的区块链跨链协作平台，致力于促进跨行业、机构和地域的跨区块链信任传递和商业合作', 113, NOW()),
('sofastack/sofa-registry', 'sofa-registry', 'SOFARegistry 是蚂蚁集团开源的具有承载海量服务注册和订阅能力的、高可用的服务注册中心，最早源自于淘宝的初版 ConfigServer，在支付宝/蚂蚁集团的业务发展驱动下，近十年间已经演进至第五代。', 112, NOW()),
('jfinal/aifei', 'Aifei', 'Aifei 是世界首个 AI Coding 框架。开创 Just Service 范式，极小化 Token 消耗、极大化 Attention 浓度，让大模型稳定生成高品质代码。', 110, NOW()),
('aizuda/easy-security', 'easy-security', '🔥🔥🔥easy-security 一款基于过过滤器实现的简单认证鉴权框架，核心只关注如何获取用户和校验，以及如何获取权限和校验，提供自定义插件，轻松扩展业务实现。', 108, NOW()),
('dromara/hodor', 'hodor', 'Hodor是一款专注于任务编排和高可用性的分布式任务调度系统。通过提供任务编程API和接口协议，使用户可以使用不同的编程语言自定义任务类型，以支持各种业务场景下的任务执行。 目前已经实现了Java任务执行器和大数据任务执行器。', 101, NOW()),
('jfinal/activerecord', 'activerecord', '由于很多小伙伴需要在非 jfinal 环境中独立使用 ActiveRecordPlugin，所以将该插件抽取成独立的项目', 101, NOW()),
('zhijiantianya/onemall', 'onemall', 'RuoYi-Vue 全新 Cloud 版本，优化重构所有功能。基于 Spring Boot + MyBatis Plus + Vue & Element 实现的后台管理系统 + 用户小程序，支持 RBAC 动态权限、多租户、数据权限、工作流', 101, NOW()),
('zhijiantianya/shenxiandao_webgame', 'shenxiandao_webgame', 'WEBGAME神仙道的开源实现。 服务端开发语言：JAVA。 目前正在努力开发中。', 74, NOW()),
('stylefeng-Roses/roses-gateway', 'roses-gateway', 'roses-gateway 微服务网关，整合spring cloud zuul，统一的鉴权，权限过滤，数据签名校验，唯一请求号生成等等，让各个微服务更注重于业务开发！', 66, NOW()),
('WeBank/WeEvent', 'WeEvent', 'Event-Driven Architecture Based on Blockchain.基于区块链的事件驱动架构', 63, NOW()),
('lionsoul/tankwar', 'tankwar', 'tankwar 是使用java开发的一个单机版的小游戏 (未使用任何游戏引擎).和90经典版的坦克大战有些不同, 这里是纯坦克之间的战争, 英雄坦克并不用保护它的家.', 61, NOW()),
('stylefeng-Roses/roses-system', 'roses-system', 'roses-system 系统管理服务，提供微服务所需要的基础服务，例如用户，组织，字典，文件，鉴权，日志等等', 60, NOW()),
('WeBank/WeBASE-Node-Manager', 'WeBASE-Node-Manager', 'WeBASE-Node-Manager处理前端页面所有web请求，管理各个节点的状态，管理链上所有智能合约，对区块链的数据进行统计、分析，对异常交易的审计，私钥管理等', 55, NOW()),
('sofastack/sofa-lookout', 'sofa-lookout', 'SOFALookout 是一个利用多维度的 metrics 对目标系统进行度量和监控的项目。SOFALookout 的多维度 metrics 参考Metrics2.0 标准。', 54, NOW()),
('sofastack/sofa-hessian', 'sofa-hessian', 'SOFA-Hessian 基于原生 Hessian v4.0.51 进行改进，目前已经蚂蚁金服内部稳定运行多年。我们修复了一些 bug，增强了一些功能，并且添加了一些特性', 53, NOW()),
('yudaocode/justauth', 'justauth', 'JustAuth，如你所见，它仅仅是一个第三方授权登录的工具类库，它可以让我们脱离繁琐的第三方登录 SDK，让登录变得So easy!', 52, NOW()),
('stylefeng-Roses/roses-biz-support', 'roses-biz-support', 'roses-biz-support 基础业务服务支撑，包含权限，组织架构，文件，字典，日志等，以jar包的方式供给别的服务使用，灵活可拆卸', 48, NOW()),
('cherishsince/ruoyi-vue-pro', 'ruoyi-vue-pro', '🔥 官方推荐  🔥 RuoYi-Vue 全新 Pro 版本，优化重构所有功能。基于 Spring Boot + MyBatis Plus + Vue & Element 实现的后台管理系统 + 微信小程序，支持 RBAC 动态权限、数据', 45, NOW()),
('aizuda/dict-trans', 'dict-trans', '🔥🔥🔥简单的字典翻译组件', 44, NOW()),
('stylefeng-Roses/roses-cloud-support', 'roses-cloud-support', 'roses-cloud-support 微服务支撑组件，包含注册中心，分布式配置中心，spring boot admin监控中心！', 42, NOW()),
('stylefeng-Roses/roses-message', 'roses-message', '分布式事务的消息中心，spring cloud分布式事务解决方案，柔性事务解决方案！', 42, NOW()),
('baomidou/mybatisplus-sharding-jdbc', 'mybatisplus-sharding-jdbc', 'mybatis-plus   sharding-jdbc   spring-boot demo', 42, NOW()),
('kekingcn/kk-erm-maven-plugin', 'kk-erm-maven-plugin', 'ER数据库模型转换jpa entity实体maven插件', 40, NOW()),
('lionsoul/elasticsearch-jcseg', 'elasticsearch-jcseg', 'elasticsearch便捷版本，集成了一些常用的插件', 36, NOW()),
('WeBank/WeBASE-Front', 'WeBASE-Front', 'WeBASE-Front是和FISCO BCOS节点配合使用的一个子系统,需要和节点统计部署，目前支持FISCO BCOS 2.0/3.0以上版本，可通过HTTP请求和节点进行通信，集成了web3sdk/java-sdk，对接口进行了封装和', 35, NOW()),
('sofastack/sofa-common-tools', 'sofa-common-tools', 'sofa-common-tools 是 SOFAStack 中间件依赖的一个通用工具包，通过自动感知应用的日志实现，提供中间件与应用隔离的日志空间打印能力', 33, NOW()),
('WeBank/WeBASE-Chain-Manager', 'WeBASE-Chain-Manager', 'WeBASE-Chain-Manager为微众区块链中间件平台-链管理服务子系统，链管理服务支持管理多条链，支持国密链、非国密链', 32, NOW()),
('lionsoul/jteach', 'jteach', 'jteach是使用java开发的一个小巧，跨平台的教学多媒体软件。', 32, NOW()),
('jfinal/jboot-admin', 'jboot-admin', 'jboot-admin是基于jboot全家桶构建的微服务实战项目，以微服务快速迭代开发为架构思想，目前包含后台管理模块、微信公众号模块，将来计划按照电商业务加入秒杀、商品、订单、app、小程序等模块。微服务模块分为api层、实体层、调用层、', 31, NOW()),
('baomidou/springmvc-hibernate-plus', 'springmvc-hibernate-plus', 'hibernate-plus演示项目', 30, NOW()),
('lionsoul/pview', 'pview', 'java开发的一个漂亮的图片查看器', 28, NOW()),
('stylefeng-Roses/roses-config-repo', 'roses-config-repo', 'roses-config-repo 配置仓库，集中维护了注册中心，网关，监控中心，系统管理服务的配置，可自由拓展其他微服务的配置！', 27, NOW()),
('dromara/solon-plugins', 'solon-plugins', '一个solon插件合集', 26, NOW()),
('sofastack/sofa-jarslink', 'sofa-jarslink', 'Jarslink 2.0 是 SOFABoot 官方基于 SOFAArk 开发的功能插件，负责管理多应用在 SOFAArk 容器之上的合并部署', 26, NOW()),
('WeBank/eggroll', 'eggroll', 'A Simple High Performance Compututing Framework for [Federated] Machine Learning', 24, NOW()),
('sofastack/sofa-acts', 'sofa-acts', 'ACTS 是基于数据模型驱动测试引擎的的新一代测试框架，它的数据以 YAML 为载体，在此上构建基于数据模型的驱动引擎，适配 TestNg+SOFABoot 的测试上下文环境', 24, NOW()),
('sofastack/sofa-rpc-boot-projects', 'sofa-rpc-boot-projects', 'rpc-sofa-boot-starter 的作用就是将 SOFARPC 功能集成到 SOFABoot 中。rpc-sofa-boot-starter 提供了统一方便的编程界面、配置方式，同时提供了 SOFABoot 的健康检查，类隔离，日', 24, NOW()),
('WeBank/WeBASE-Codegen-Monkey', 'WeBASE-Codegen-Monkey', 'WeBASE-Codegen-Monkey是WeBASE数据导出工具的代码生成组件，可帮助用户自动生成基于FISCO BCOS的数据导出组件WeBASE-Collect-Bee', 21, NOW()),
('WeBank/WeBASE-Sign', 'WeBASE-Sign', '签名服务子系统。功能：管理公私钥、对数据进行签名', 21, NOW()),
('WeBank/WeBASE-Solidity-Security', 'WeBASE-Solidity-Security', '', 21, NOW()),
('WeBank/WeCross-Java-SDK', 'WeCross-Java-SDK', 'WeCross-Java-SDK为WeCross提供Java API。开发者通过SDK可以方便快捷地基于WeCross开发自己的跨链应用', 20, NOW()),
('WeBank/WeCross-Fabric1-Stub', 'WeCross-Fabric1-Stub', 'WeCross Fabric1 Stub是WeCross用于适配Hyperledger Fabric 1.4及以上版本的插件', 20, NOW()),
('WeBank/WeCross-Console', 'WeCross-Console', 'WeCross控制台是WeCross的重要交互式客户端工具', 20, NOW()),
('WeBank/WeBASE-Collect-Bee', 'WeBASE-Collect-Bee', 'WeBASE-Collect-Bee 是一个基于FISCO-BCOS平台的数据导出工具', 20, NOW()),
('WeBank/WeBASE-Transaction', 'WeBASE-Transaction', 'WeBASE-Transaction是交易上链代理子系统。主要接收无状态交易请求，缓存到数据库中，再异步上链', 20, NOW()),
('jfinal/aifei-eco', 'Aifei Ecosystem', 'Aifei 生态。Aifei AI Coding framework ecosystem: plugins, integrations, and examples.', 20, NOW()),
('jfinal/cos', 'cos', 'cos upload file', 20, NOW()),
('WeBank/Dockin-RM', 'Dockin-RM', 'Dockin容器平台资源管理器', 19, NOW()),
('WeBank/WeIdentity-Build-Tools', 'WeIdentity-Build-Tools', 'WeIdentity JAVA SDK安装部署工具', 18, NOW()),
('lionsoul/dclock', 'dclock', 'java开发的一款精美的桌面闹钟', 18, NOW()),
('macrozheng/springcloud-config', 'springcloud-config', '', 16, NOW()),
('dromara/easy-tl', 'EasyTL', '一个功能丰富的轻量级字符串模板引擎，支持类 JavaScript 的表达式语法、控制流语句（if/for/switch）、高级特性（空安全操作符、Elvis 表达式、正则匹配、区间字面量等）', 14, NOW()),
('jfinal/Jfinal-layui', 'Jfinal-layui', 'jfinal+layui极速开发企业应用管理系统，是以jfinal+layui为核心的企业应用项目架构，利用jfinal的特性与layui完美结合，达到快速启动项目的目的。让开发更简单高效，即使你不会layui，也能轻松掌握使用。该项目的核', 12, NOW()),
('jfinal/LMS', 'LMS', '基于Jfinal3.1、Shiro的实践', 12, NOW()),
('stylefeng/xjar', 'xjar', 'Spring Boot JAR 安全加密运行工具，同时支持的原生JAR。 基于对JAR包内资源的加密以及拓展ClassLoader来构建的一套程序加密启动，动态解密运行的方案，避免源码泄露或反编译。', 11, NOW()),
('jfinal/enjoy-performance', 'enjoy-performance', 'enjoy performance', 11, NOW()),
('macrozheng/mall-config', 'mall-config', 'mall 项目配置存储', 10, NOW()),
('jfinal/JFinal-ext2', 'JFinal-ext2', 'JFinal-ext2', 8, NOW()),
('kekingcn/quarkus-redis-klock', 'quarkus-redis-klock', 'quarkus的分布式锁框架', 8, NOW()),
('zhijiantianya/x-traveller', 'x-traveller', 'x项目后端', 8, NOW()),
('stylefeng/roses-config', 'roses-config', 'Roses的配置服务器', 7, NOW()),
('jfinal/JDoc', 'JDoc', 'JDoc是一个用JAVA语言开发的接口文档生成器，利用极简配置就可实现接口文档的生成，避免开发人员花时间去维护接口文档，导致更新不及时，维护困难问题，目前支持JFinal，SpingMVC,SpringBoot框架，格式支持html文档格式', 7, NOW()),
('jfinal/aij', 'aij', 'AiJ是一套完整的房间类游戏解决方案，支持无限水平扩展来满足更大的人数承载，并且提供了良好的调试接口，主要技术为Java、typescript 非常适合Java技术栈的同学入门游戏开发。', 6, NOW());

